### PR TITLE
PHP 5.3 fixes for Session->getStatus()

### PR DESCRIPTION
**Pull request by armatronic**

### CODE REVIEW

**Comment by armatronic** [comment]
Sorry to bring this up again, but has anyone had a chance to look over this? I've tested it in my own project under 5.3 and it works.

**Comment by harikt** [comment]
nope. I haven't tested this. Paul will look into this. The priority being given to router, dispatcher, di . So this may take some time. 
Be a bit more patient and thank you.

**Comment by armatronic** [comment]
No worries - thanks for letting me know what was happening.

**Comment by harikt** [comment]
@armatronic are you not in google groups ? We don't have that much mails coming, so do subscribe if you have not.

Thank you.

**Comment by pmjones** [comment]
@armatronic: Thank you for this -- I think it's a move in the right direction. Some notes:
- I don't think we should be declaring functions in the global namespace. I would prefer to see the a method on the Session class (or elsewhere) that uses the function if available, and uses the replacement code if not.
- We don't need the extra require-dev lines in composer.json; these introduce dependencies that can be handled otherwise.

If you would like to revise this PR with those notes in mind, I can merge it directly from Github so you automatically get credit. Otherwise, if you don't have time, I can merge it manually, edit it, and then commit with your name in the log message, but I don't think Github adds you to the contributors page automatically then.

**Comment by armatronic** [comment]
Hi, sorry about the late reply - I've been on vacation.

Good idea regarding the global namespace function, I wasn't sure about the best way to proceed with this. I'll fix this and remove the require-dev lines, and update the PR.

**Comment by pmjones** [comment]
Accepting this as-is, with the caveat that I reserve the right to modify as needed. Thanks very much for the 5.3 compatibility!

**Pull request merged**
