### PR TITLE
Use SegmentInterface as typehint

### PR DESCRIPTION
**Pull request by Khartir**
The typehint for the Segment in CsrfToken should be the interface, not the implementation.

### CODE REVIEW

**Comment by harikt** [comment]
We need to update travis and composer.json to fix the build.

I don't have any trouble merging this PR. @auraphp/docs-team do you have any thoughts about these change ?

**Comment by koriym** [comment]
@harikt I agreed with @Khartir.

**Comment by harikt** [comment]
Thank you @koriym .

**Comment by harikt** [comment]
I am merging this PR for the current time. Will wait for @pmjones thoughts before we make a release.

**Pull request merged**
