### PR TITLE
Added remove( \$key = null) method to Segment object

### PR DESCRIPTION
**Pull request by epoplive**

### CODE REVIEW

**Comment by harikt** [comment]
You are changing the interface. If you change interface it is BC break.

**Comment by epoplive** [comment]
I would disagree, I've added to the interface, not modified any existing methods.  I think this method is necessary as it encapsulated what is required functionality for many users.  Otherwise many use cases require accessing the $_SESSION array directly (which becomes extra dirty as there is no public access to Segment::name directly or via accessor method).  As this is the current version of the software, this seems like the correct place.  If you need to ensure no new functionality, you can pin to a specific version via composer.

P.S.  If you don't like additional features, you may not like the pull requests I have planned.  ;)

**Comment by harikt** [comment]
You can add a method, but not modify an Interface . Say someone made use of the Interface, then he should also add the same method, else things break.

> P.S. If you don't like additional features, you may not like the pull requests I have planned. ;)

There are other people, who may like the feature. I was only representing my views.

And there is something already you can do 

``` php
$session_factory = new \Aura\Session\SessionFactory;
$session = $session_factory->newInstance($_COOKIE);
$segment = $session->getSegment('Vendor\Package\ClassName');
// clear all session
$segment->clear();
```

I do understand there is no way to remove only a specific key other than setting it to null. We can add the remove method to segment, but not on Interface. And may be this will be a good candidate for 3.x .

**Comment by epoplive** [comment]
I'm not looking to clear the segment, I need to remove a single value.  I don't think you seem to understand the concept of backwards compatibility.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa373574%28v=vs.85%29.aspx

If you'd like I can do some more googling for you, but I can give you thousands if not millions of articles on modifying interfaces without breaking backwards compatibility.  You simply don't know what you're talking about here.  

If people used your logic, you could never make a modification past the initial commit of the interface.  I don't know about you, but I often write my code over the course of more than one session and it's not always perfect the first time.   

https://github.com/auraphp/Aura.Session/commits/2.x/src/SegmentInterface.php

The commit log itself from the repo says you don't know what you're talking about.

**Comment by harikt** [comment]
sure :) . 

As I said there are other people over here who knows well than me. You will hear what they feel.

Thank you

**Comment by epoplive** [comment]
talked with pmjones, he's going to fork a 3.x branch so I can start making pull requests against that.  Problem solved for everyone it sounds like.

**Pull request closed without merging**
